import type { SongCatalogEntry } from "../song-buckets";

export const balkanSongAdditions = [
  {
    id: "bijelo-dugme-djurdjevdan",
    title: "Đurđevdan",
    artist: "Bijelo Dugme",
    youtubeUrl: "https://www.youtube.com/watch?v=--MTkvC7UZ0",
    clipStartSeconds: 55,
    bucketIds: ["balkan", "rock-classics", "throwbacks"],
  },
  {
    id: "zdravko-colic-ti-si-mi-u-krvi",
    title: "Ti si mi u krvi",
    artist: "Zdravko Čolić",
    youtubeUrl: "https://www.youtube.com/watch?v=9nBnRu6o4sM",
    clipStartSeconds: 74,
    bucketIds: ["balkan", "throwbacks"],
  },
  {
    id: "oliver-dragojevic-cesarica",
    title: "Cesarica",
    artist: "Oliver Dragojević",
    youtubeUrl: "https://www.youtube.com/watch?v=4lWgvFQX2MM",
    clipStartSeconds: 55,
    bucketIds: ["balkan", "throwbacks"],
  },
  {
    id: "bajaga-moji-drugovi",
    title: "Moji drugovi",
    artist: "Bajaga i Instruktori",
    youtubeUrl: "https://www.youtube.com/watch?v=M1wjo8AGfaM",
    clipStartSeconds: 18,
    bucketIds: ["balkan", "rock-classics", "throwbacks"],
  },
  {
    id: "parni-valjak-sve-jos-mirise-na-nju",
    title: "Sve još miriše na nju",
    artist: "Parni Valjak",
    youtubeUrl: "https://www.youtube.com/watch?v=coEMbzlkzV4",
    clipStartSeconds: 63,
    bucketIds: ["balkan", "rock-classics", "throwbacks"],
  },
  {
    id: "prljavo-kazaliste-mojoj-majci",
    title: "Mojoj majci",
    artist: "Prljavo Kazalište",
    youtubeUrl: "https://www.youtube.com/watch?v=18BQF7tjsLM",
    clipStartSeconds: 75,
    bucketIds: ["balkan", "rock-classics", "throwbacks"],
  },
  {
    id: "crvena-jabuka-tugo-nesreco",
    title: "Tugo, nesrećo",
    artist: "Crvena Jabuka",
    youtubeUrl: "https://www.youtube.com/watch?v=xAaikVv7kWA",
    clipStartSeconds: 45,
    bucketIds: ["balkan", "rock-classics", "throwbacks"],
  },
  {
    id: "dino-merlin-kad-si-rekla-da-me-volis",
    title: "Kad si rekla da me voliš",
    artist: "Dino Merlin",
    youtubeUrl: "https://www.youtube.com/watch?v=bw10euhE--8",
    clipStartSeconds: 70,
    bucketIds: ["balkan", "2000s", "throwbacks"],
  },
  {
    id: "zeljko-joksimovic-lane-moje",
    title: "Lane moje",
    artist: "Željko Joksimović",
    youtubeUrl: "https://www.youtube.com/watch?v=z7OvpjplJ_8",
    clipStartSeconds: 47,
    bucketIds: ["balkan", "2000s", "eurovision", "throwbacks"],
  },
  {
    id: "marija-serifovic-molitva",
    title: "Molitva",
    artist: "Marija Šerifović",
    youtubeUrl: "https://www.youtube.com/watch?v=FSueQN1QvV4",
    clipStartSeconds: 53,
    bucketIds: ["balkan", "2000s", "eurovision", "throwbacks"],
  },
  {
    id: "severina-moja-stikla",
    title: "Moja štikla",
    artist: "Severina",
    youtubeUrl: "https://www.youtube.com/watch?v=hGp3YfEj_GY",
    clipStartSeconds: 39,
    bucketIds: ["balkan", "2000s", "eurovision", "throwbacks"],
  },
  {
    id: "hari-mata-hari-lejla",
    title: "Lejla",
    artist: "Hari Mata Hari",
    youtubeUrl: "https://www.youtube.com/watch?v=SXlIN3mcsH4",
    clipStartSeconds: 45,
    bucketIds: ["balkan", "2000s", "eurovision", "throwbacks"],
  },
  {
    id: "dubioza-kolektiv-kazu",
    title: "Kažu",
    artist: "Dubioza Kolektiv",
    youtubeUrl: "https://www.youtube.com/watch?v=FZZJeMKJV3M",
    clipStartSeconds: 47,
    bucketIds: ["balkan", "2010s"],
  },
  {
    id: "senidah-sladjana",
    title: "Slađana",
    artist: "Senidah",
    youtubeUrl: "https://www.youtube.com/watch?v=VMj1viq9KmA",
    clipStartSeconds: 46,
    bucketIds: ["balkan", "2010s"],
  },
  {
    id: "konstrakta-in-corpore-sano",
    title: "In Corpore Sano",
    artist: "Konstrakta",
    youtubeUrl: "https://www.youtube.com/watch?v=3S1jrYq87Zw",
    clipStartSeconds: 51,
    bucketIds: ["balkan", "eurovision"],
  },
  {
    id: "baby-lasagna-rim-tim-tagi-dim",
    title: "Rim Tim Tagi Dim",
    artist: "Baby Lasagna",
    youtubeUrl: "https://www.youtube.com/watch?v=kmg8EAD-Kjw",
    clipStartSeconds: 47,
    bucketIds: ["balkan", "eurovision"],
  },
  {
    id: "hurricane-loco-loco",
    title: "Loco Loco",
    artist: "Hurricane",
    youtubeUrl: "https://www.youtube.com/watch?v=FSTMz-_kbVQ",
    clipStartSeconds: 50,
    bucketIds: ["balkan", "eurovision", "dance-edm"],
  },
  {
    id: "teya-dora-ramonda",
    title: "Ramonda",
    artist: "Teya Dora",
    youtubeUrl: "https://www.youtube.com/watch?v=jm7jy2471vI",
    clipStartSeconds: 62,
    bucketIds: ["balkan", "eurovision"],
  },
  {
    id: "jala-buba-coby-ona-e",
    title: "Ona'e",
    artist: "Jala Brat, Buba Corelli & Coby",
    youtubeUrl: "https://www.youtube.com/watch?v=iyPgQN2wLjs",
    clipStartSeconds: 37,
    bucketIds: ["balkan", "2010s"],
  },
  {
    id: "severina-ministarke-uno-momento",
    title: "Uno momento",
    artist: "Severina feat. Ministarke",
    youtubeUrl: "https://www.youtube.com/watch?v=Gvchbkh4jQY",
    clipStartSeconds: 47,
    bucketIds: ["balkan", "2010s", "dance-edm"],
  },
] as const satisfies readonly SongCatalogEntry[];
