import { type SongCatalogEntry } from "../song-buckets";

export const coreSongCatalog = [
  {
    id: "bohemian-rhapsody",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    youtubeUrl: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "rock-classics", "throwbacks"],
  },
  {
    id: "take-on-me",
    title: "Take On Me",
    artist: "a-ha",
    youtubeUrl: "https://www.youtube.com/watch?v=djV11Xbc914",
    clipStartSeconds: 22,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "smells-like-teen-spirit",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    youtubeUrl: "https://www.youtube.com/watch?v=hTWKbfoikeg",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "rock-classics", "throwbacks"],
  },
  {
    id: "billie-jean",
    title: "Billie Jean",
    artist: "Michael Jackson",
    youtubeUrl: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "rolling-in-the-deep",
    title: "Rolling In The Deep",
    artist: "Adele",
    youtubeUrl: "https://www.youtube.com/watch?v=rYEDA3JcQqw",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "blinding-lights",
    title: "Blinding Lights",
    artist: "The Weeknd",
    youtubeUrl: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    clipStartSeconds: 24,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "bad-guy",
    title: "bad guy",
    artist: "Billie Eilish",
    youtubeUrl: "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    clipStartSeconds: 17,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "bara-bada-bastu",
    title: "Bara Bada Bastu",
    artist: "KAJ",
    youtubeUrl: "https://www.youtube.com/watch?v=QOehBj0nCMU",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "meme", "eurovision"],
  },
  {
    id: "berghain",
    title: "Berghain",
    artist: "ROSALIA",
    youtubeUrl: "https://www.youtube.com/watch?v=htQBS2Ikz6c",
    clipStartSeconds: 26,
    bucketIds: ["global-pop"],
  },
  {
    id: "francesca",
    title: "Francesca",
    artist: "Hozier",
    youtubeUrl: "https://www.youtube.com/watch?v=K1u_hL11auM",
    clipStartSeconds: 13,
    bucketIds: ["global-pop"],
  },
  {
    id: "runaway",
    title: "Runaway",
    artist: "Kanye West",
    youtubeUrl: "https://www.youtube.com/watch?v=cv1naUa3_3g",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "moja-treba",
    title: "Moja treba",
    artist: "Ajkule",
    youtubeUrl: "https://www.youtube.com/watch?v=RgRfmL73qzU",
    clipStartSeconds: 30,
    bucketIds: ["balkan"],
  },
  {
    id: "najjaci-si",
    title: "NAJJACI SI",
    artist: "MIKIC",
    youtubeUrl: "https://www.youtube.com/watch?v=MdxGibK0S4A",
    clipStartSeconds: 30,
    bucketIds: ["balkan", "meme"],
  },
  {
    id: "the-7th-element",
    title: "The 7th Element",
    artist: "Vitas",
    youtubeUrl: "https://www.youtube.com/watch?v=989-7xsRLR4",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks"],
  },
  {
    id: "zmija-i-zaba",
    title: "Zmija i zaba",
    artist: "Oskar i Slavica Cukteras",
    youtubeUrl: "https://www.youtube.com/watch?v=8hczXIpeZqI",
    clipStartSeconds: 30,
    bucketIds: ["balkan"],
  },
  {
    id: "aspirin",
    title: "Aspirin",
    artist: "Seka",
    youtubeUrl: "https://www.youtube.com/watch?v=gH0xuHo8x0g",
    clipStartSeconds: 30,
    bucketIds: ["balkan"],
  },
  {
    id: "koktel-ljubavi",
    title: "Koktel ljubavi",
    artist: "Nedeljko Bajic Baja",
    youtubeUrl: "https://www.youtube.com/watch?v=ZM5CuiuGkaA",
    clipStartSeconds: 30,
    bucketIds: ["balkan"],
  },
  {
    id: "kuku-lele",
    title: "Kuku Lele",
    artist: "Magnifico",
    youtubeUrl: "https://www.youtube.com/watch?v=AmByNZfSYZI",
    clipStartSeconds: 30,
    bucketIds: ["slovenian", "balkan"],
  },
  {
    id: "barbie-and-ken",
    title: "Barbie & Ken",
    artist: "MIKIC",
    youtubeUrl: "https://www.youtube.com/watch?v=mWX0eKTiHcY",
    clipStartSeconds: 30,
    bucketIds: ["balkan", "meme"],
  },
  {
    id: "silvo",
    title: "Silvo",
    artist: "KOKOSY",
    youtubeUrl: "https://www.youtube.com/watch?v=IUyHxk9afs8",
    clipStartSeconds: 30,
    bucketIds: ["slovenian"],
  },
  {
    id: "youre-beautiful-but-its-groan-tube",
    title: "You're Beautiful",
    artist: "Groan Tube",
    youtubeUrl: "https://www.youtube.com/watch?v=XglGUAV2iKU",
    clipStartSeconds: 30,
    bucketIds: ["meme"],
  },
  {
    id: "london-song",
    title: "London Song",
    artist: "Ninajirachi",
    youtubeUrl: "https://www.youtube.com/watch?v=mra_6tIHLYg",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "dance-edm"],
  },
  {
    id: "kej-si",
    title: "Kej si",
    artist: "Generator",
    youtubeUrl: "https://www.youtube.com/watch?v=ooGHONDhFPQ",
    clipStartSeconds: 10,
    bucketIds: ["slovenian"],
  },
  {
    id: "creva-na-plot",
    title: "Creva na plot",
    artist: "Slon in Sadez",
    youtubeUrl: "https://www.youtube.com/watch?v=5w5m8lYMJoo",
    clipStartSeconds: 30,
    bucketIds: ["slovenian", "meme"],
  },
  {
    id: "all-my-friends-are-dead",
    title: "All My Friends Are Dead",
    artist: "MRFY",
    youtubeUrl: "https://www.youtube.com/watch?v=GfCDwegih70",
    clipStartSeconds: 30,
    bucketIds: ["slovenian"],
    forcedOptionSongId: "prjatucki",
  },
  {
    id: "prjatucki",
    title: "Prjatucki ♥",
    artist: "MRFY",
    youtubeUrl: "https://www.youtube.com/watch?v=yZZtyN_EfK8",
    clipStartSeconds: 30,
    bucketIds: ["slovenian"],
    forcedOptionSongId: "all-my-friends-are-dead",
  },
  {
    id: "never-gonna-give-you-up",
    title: "Never Gonna Give You Up",
    artist: "Rick Astley",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks"],
  },
  {
    id: "ppap",
    title: "PPAP (Pen Pineapple Apple Pen)",
    artist: "PIKOTARO",
    youtubeUrl: "https://www.youtube.com/watch?v=Ct6BUPvE2sM",
    clipStartSeconds: 30,
    bucketIds: ["meme", "2010s"],
  },
  {
    id: "sandstorm",
    title: "Sandstorm",
    artist: "Darude",
    youtubeUrl: "https://www.youtube.com/watch?v=y6120QOlsfU",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks", "dance-edm"],
  },
  {
    id: "crab-rave",
    title: "Crab Rave",
    artist: "Noisestorm",
    youtubeUrl: "https://www.youtube.com/watch?v=_upPCdWq11k",
    clipStartSeconds: 30,
    bucketIds: ["meme", "2010s", "dance-edm"],
  },
  {
    id: "running-in-the-90s",
    title: "Running In The 90s",
    artist: "Max Coveri",
    youtubeUrl: "https://www.youtube.com/watch?v=kxLwGow0Tvw",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks", "dance-edm"],
  },
  {
    id: "scatman",
    title: "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)",
    artist: "Scatman John",
    youtubeUrl: "https://www.youtube.com/watch?v=Hy8kmNEo1i8",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks", "dance-edm"],
  },
  {
    id: "baby-im-yours",
    title: "Baby I'm Yours",
    artist: "Breakbot feat. Irfane",
    youtubeUrl: "https://www.youtube.com/watch?v=6okxuiiHx2w",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "dance-edm"],
  },
  {
    id: "coffin-dance",
    title: "Coffin Dance",
    artist: "Vicetone & Tony Igy",
    youtubeUrl: "https://www.youtube.com/watch?v=j9V78UbdzWI",
    clipStartSeconds: 30,
    bucketIds: ["meme", "2010s", "dance-edm"],
  },
  {
    id: "buttercup",
    title: "Buttercup",
    artist: "Jack Stauber",
    youtubeUrl: "https://www.youtube.com/watch?v=eYDI8b5Nn5s",
    clipStartSeconds: 30,
    bucketIds: ["meme", "2010s"],
  },
  {
    id: "jerk-it-out",
    title: "Jerk It Out",
    artist: "Caesars Palace",
    youtubeUrl: "https://www.youtube.com/watch?v=w869Avr_fXI",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2000s"],
  },
  {
    id: "all-star",
    title: "All Star",
    artist: "Smash Mouth",
    youtubeUrl: "https://www.youtube.com/watch?v=L_jWHffIx5E",
    clipStartSeconds: 30,
    bucketIds: ["meme", "throwbacks"],
  },
  {
    id: "lemon-tree",
    title: "Lemon Tree",
    artist: "Fools Garden",
    youtubeUrl: "https://www.youtube.com/watch?v=Va0vs1fhhNI",
    clipStartSeconds: 30,
    bucketIds: ["throwbacks"],
  },
  {
    id: "ymca",
    title: "YMCA",
    artist: "Village People",
    youtubeUrl: "https://www.youtube.com/watch?v=CS9OO0S5w2k",
    clipStartSeconds: 30,
    bucketIds: ["throwbacks", "rock-classics"],
  },
  {
    id: "gangnam-style",
    title: "Gangnam Style",
    artist: "PSY",
    youtubeUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    clipStartSeconds: 30,
    bucketIds: ["meme", "global-pop", "2010s"],
  },
  {
    id: "dancing-queen-abba",
    title: "Dancing Queen",
    artist: "ABBA",
    youtubeUrl: "https://www.youtube.com/watch?v=xFrGuyw1V8s",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "stayin-alive-bee-gees",
    title: "Stayin' Alive",
    artist: "Bee Gees",
    youtubeUrl: "https://www.youtube.com/watch?v=I_izvAbhExY",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "september-earth-wind-fire",
    title: "September",
    artist: "Earth, Wind & Fire",
    youtubeUrl: "https://www.youtube.com/watch?v=Gs069dndIYk",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "i-will-survive-gloria-gaynor",
    title: "I Will Survive",
    artist: "Gloria Gaynor",
    youtubeUrl: "https://www.youtube.com/watch?v=gYkACVDFmeg",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "rocket-man-elton-john",
    title: "Rocket Man",
    artist: "Elton John",
    youtubeUrl: "https://www.youtube.com/watch?v=DtVBCG6ThDk",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "thriller-michael-jackson",
    title: "Thriller",
    artist: "Michael Jackson",
    youtubeUrl: "https://www.youtube.com/watch?v=sOnqjkJTMaA",
    clipStartSeconds: 258,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "i-wanna-dance-with-somebody-whitney-houston",
    title: "I Wanna Dance With Somebody",
    artist: "Whitney Houston",
    youtubeUrl: "https://www.youtube.com/watch?v=eH3giaIzONA",
    clipStartSeconds: 23,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "girls-just-want-to-have-fun-cyndi-lauper",
    title: "Girls Just Want To Have Fun",
    artist: "Cyndi Lauper",
    youtubeUrl: "https://www.youtube.com/watch?v=PIb6AZdTr-A",
    clipStartSeconds: 31,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "like-a-prayer-madonna",
    title: "Like A Prayer",
    artist: "Madonna",
    youtubeUrl: "https://www.youtube.com/watch?v=79fzeNUqQbQ",
    clipStartSeconds: 25,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "wonderwall-oasis",
    title: "Wonderwall",
    artist: "Oasis",
    youtubeUrl: "https://www.youtube.com/watch?v=bx1Bh8ZvH84",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "wannabe-spice-girls",
    title: "Wannabe",
    artist: "Spice Girls",
    youtubeUrl: "https://www.youtube.com/watch?v=gJLIiF15wjQ",
    clipStartSeconds: 28,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "baby-one-more-time-britney-spears",
    title: "...Baby One More Time",
    artist: "Britney Spears",
    youtubeUrl: "https://www.youtube.com/watch?v=C-u5WLJ9Yk4",
    clipStartSeconds: 15,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "i-want-it-that-way-backstreet-boys",
    title: "I Want It That Way",
    artist: "Backstreet Boys",
    youtubeUrl: "https://www.youtube.com/watch?v=4fndeDfaWCg",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "throwbacks"],
  },
  {
    id: "creep-radiohead",
    title: "Creep",
    artist: "Radiohead",
    youtubeUrl: "https://www.youtube.com/watch?v=XFkzRNyygfk",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "hey-ya-outkast",
    title: "Hey Ya!",
    artist: "Outkast",
    youtubeUrl: "https://www.youtube.com/watch?v=PWgvGjAhvIw",
    clipStartSeconds: 48,
    bucketIds: ["global-pop", "throwbacks", "2000s"],
  },
  {
    id: "mr-brightside-the-killers",
    title: "Mr. Brightside",
    artist: "The Killers",
    youtubeUrl: "https://www.youtube.com/watch?v=gGdGFtwCNBE",
    clipStartSeconds: 30,
    bucketIds: ["rock-classics", "throwbacks", "2000s"],
  },
  {
    id: "crazy-in-love-beyonce",
    title: "Crazy In Love",
    artist: "Beyoncé",
    youtubeUrl: "https://www.youtube.com/watch?v=ViwtNLUqkMY",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2000s"],
  },
  {
    id: "lose-yourself-eminem",
    title: "Lose Yourself",
    artist: "Eminem",
    youtubeUrl: "https://www.youtube.com/watch?v=_Yhyp-_hX2s",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2000s"],
  },
  {
    id: "viva-la-vida-coldplay",
    title: "Viva La Vida",
    artist: "Coldplay",
    youtubeUrl: "https://www.youtube.com/watch?v=dvgZkm1xWPE",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "rock-classics", "2000s"],
  },
  {
    id: "bad-romance-lady-gaga",
    title: "Bad Romance",
    artist: "Lady Gaga",
    youtubeUrl: "https://www.youtube.com/watch?v=qrO4YZeyl0I",
    clipStartSeconds: 37,
    bucketIds: ["global-pop", "2000s"],
  },
  {
    id: "umbrella-rihanna",
    title: "Umbrella",
    artist: "Rihanna",
    youtubeUrl: "https://www.youtube.com/watch?v=CvBfHwUxHIk",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2000s"],
  },
  {
    id: "uptown-funk-mark-ronson-ft-bruno-mars",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    youtubeUrl: "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    clipStartSeconds: 16,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "shape-of-you-ed-sheeran",
    title: "Shape of You",
    artist: "Ed Sheeran",
    youtubeUrl: "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    clipStartSeconds: 30,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "despacito-luis-fonsi",
    title: "Despacito",
    artist: "Luis Fonsi",
    youtubeUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    clipStartSeconds: 19,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "blank-space-taylor-swift",
    title: "Blank Space",
    artist: "Taylor Swift",
    youtubeUrl: "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    clipStartSeconds: 25,
    bucketIds: ["global-pop", "2010s"],
  },
  {
    id: "levitating-dua-lipa",
    title: "Levitating",
    artist: "Dua Lipa",
    youtubeUrl: "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "as-it-was-harry-styles",
    title: "As It Was",
    artist: "Harry Styles",
    youtubeUrl: "https://www.youtube.com/watch?v=H5v3kku4y6Q",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "flowers-miley-cyrus",
    title: "Flowers",
    artist: "Miley Cyrus",
    youtubeUrl: "https://www.youtube.com/watch?v=G7KNmW9a75Y",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "drivers-license-olivia-rodrigo",
    title: "drivers license",
    artist: "Olivia Rodrigo",
    youtubeUrl: "https://www.youtube.com/watch?v=ZmDBbnmKpqQ",
    clipStartSeconds: 30,
    bucketIds: ["global-pop"],
  },
  {
    id: "kill-bill-sza",
    title: "Kill Bill",
    artist: "SZA",
    youtubeUrl: "https://www.youtube.com/watch?v=SQnc1QibapQ",
    clipStartSeconds: 35,
    bucketIds: ["global-pop"],
  },
] as const satisfies readonly SongCatalogEntry[];
