import { type SongCatalogSourceEntry } from "../song-buckets";

export const internationalSongAdditions = [
  {
    id: "euphoria-loreen",
    title: "Euphoria",
    artist: "Loreen",
    youtubeUrl: "https://www.youtube.com/watch?v=Pfo-8z86x80",
    clipStartSeconds: 55,
    bucketIds: ["eurovision", "dance-edm", "2010s", "global-pop"],
  },
  {
    id: "zitti-e-buoni-maneskin",
    title: "Zitti e buoni",
    artist: "Måneskin",
    youtubeUrl: "https://www.youtube.com/watch?v=RVH5dn1cxAQ",
    clipStartSeconds: 48,
    bucketIds: ["eurovision", "global-pop"],
  },
  {
    id: "rise-like-a-phoenix-conchita-wurst",
    title: "Rise Like a Phoenix",
    artist: "Conchita Wurst",
    youtubeUrl: "https://www.youtube.com/watch?v=ToqNa0rqUtY",
    clipStartSeconds: 60,
    bucketIds: ["eurovision", "2010s", "global-pop"],
  },
  {
    id: "fairytale-alexander-rybak",
    title: "Fairytale",
    artist: "Alexander Rybak",
    youtubeUrl: "https://www.youtube.com/watch?v=WXwgZL4zx9o",
    clipStartSeconds: 48,
    bucketIds: ["eurovision", "2000s", "global-pop", "throwbacks"],
  },
  {
    id: "hard-rock-hallelujah-lordi",
    title: "Hard Rock Hallelujah",
    artist: "Lordi",
    youtubeUrl: "https://www.youtube.com/watch?v=gAh9NRGNhUU",
    clipStartSeconds: 52,
    bucketIds: ["eurovision", "2000s", "rock-classics", "throwbacks"],
  },
  {
    id: "cha-cha-cha-kaarija",
    title: "Cha Cha Cha",
    artist: "Käärijä",
    youtubeUrl: "https://www.youtube.com/watch?v=rNrgQm5z07U",
    clipStartSeconds: 39,
    bucketIds: ["eurovision", "dance-edm", "global-pop", "meme"],
  },
  {
    id: "dancing-lasha-tumbai-verka-serduchka",
    title: "Dancing Lasha Tumbai",
    artist: "Verka Serduchka",
    youtubeUrl: "https://www.youtube.com/watch?v=hfjHJneVonE",
    clipStartSeconds: 49,
    bucketIds: ["eurovision", "2000s", "dance-edm", "meme", "throwbacks"],
  },
  {
    id: "wild-dances-ruslana",
    title: "Wild Dances",
    artist: "Ruslana",
    youtubeUrl: "https://www.youtube.com/watch?v=10XR67NQcAc",
    clipStartSeconds: 43,
    bucketIds: ["eurovision", "2000s", "dance-edm", "throwbacks"],
  },
  {
    id: "heroes-mans-zelmerlow",
    title: "Heroes",
    artist: "Måns Zelmerlöw",
    youtubeUrl: "https://www.youtube.com/watch?v=5sGOwFVUU0I",
    clipStartSeconds: 54,
    bucketIds: ["eurovision", "dance-edm", "2010s", "global-pop"],
  },
  {
    id: "wake-me-up-avicii",
    title: "Wake Me Up",
    artist: "Avicii",
    youtubeUrl: "https://www.youtube.com/watch?v=IcrbM1l_BoI",
    clipStartSeconds: 62,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "titanium-david-guetta-sia",
    title: "Titanium",
    artist: "David Guetta feat. Sia",
    youtubeUrl: "https://www.youtube.com/watch?v=JRfuAukYTKg",
    clipStartSeconds: 62,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "summer-calvin-harris",
    title: "Summer",
    artist: "Calvin Harris",
    youtubeUrl: "https://www.youtube.com/watch?v=ebXbLfLACGM",
    clipStartSeconds: 48,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "dont-you-worry-child-swedish-house-mafia",
    title: "Don't You Worry Child",
    artist: "Swedish House Mafia feat. John Martin",
    youtubeUrl: "https://www.youtube.com/watch?v=1y6smkh6c-0",
    clipStartSeconds: 67,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "party-rock-anthem-lmfao",
    title: "Party Rock Anthem",
    artist: "LMFAO feat. Lauren Bennett & GoonRock",
    youtubeUrl: "https://www.youtube.com/watch?v=KQ6zr6kCPj8",
    clipStartSeconds: 50,
    bucketIds: ["dance-edm", "2010s", "global-pop", "meme"],
  },
  {
    id: "lean-on-major-lazer-dj-snake",
    title: "Lean On",
    artist: "Major Lazer & DJ Snake feat. MØ",
    youtubeUrl: "https://www.youtube.com/watch?v=YqeW9_5kURI",
    clipStartSeconds: 42,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "clarity-zedd",
    title: "Clarity",
    artist: "Zedd feat. Foxes",
    youtubeUrl: "https://www.youtube.com/watch?v=IxxstCcJlsc",
    clipStartSeconds: 57,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "rather-be-clean-bandit",
    title: "Rather Be",
    artist: "Clean Bandit feat. Jess Glynne",
    youtubeUrl: "https://www.youtube.com/watch?v=m-M1AtrxztU",
    clipStartSeconds: 48,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
  {
    id: "one-more-time-daft-punk",
    title: "One More Time",
    artist: "Daft Punk",
    youtubeUrl: "https://www.youtube.com/watch?v=FGBhQbmPwH8",
    clipStartSeconds: 47,
    bucketIds: ["dance-edm", "2000s", "global-pop", "throwbacks"],
  },
  {
    id: "everytime-we-touch-cascada",
    title: "Everytime We Touch",
    artist: "Cascada",
    youtubeUrl: "https://www.youtube.com/watch?v=4G6QDNC4jPs",
    clipStartSeconds: 36,
    bucketIds: ["dance-edm", "2000s", "global-pop", "throwbacks"],
  },
  {
    id: "in-the-end-linkin-park",
    title: "In the End",
    artist: "Linkin Park",
    youtubeUrl: "https://www.youtube.com/watch?v=eVTXPUF4Oz4",
    clipStartSeconds: 8,
    bucketIds: ["2000s", "rock-classics", "throwbacks"],
  },
  {
    id: "toxic-britney-spears",
    title: "Toxic",
    artist: "Britney Spears",
    youtubeUrl: "https://www.youtube.com/watch?v=LOZuxwVk7TU",
    clipStartSeconds: 15,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "seven-nation-army-the-white-stripes",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    youtubeUrl: "https://www.youtube.com/watch?v=0J2QdDbelmY",
    clipStartSeconds: 8,
    bucketIds: ["2000s", "rock-classics", "throwbacks"],
  },
  {
    id: "complicated-avril-lavigne",
    title: "Complicated",
    artist: "Avril Lavigne",
    youtubeUrl: "https://www.youtube.com/watch?v=5NPBIwQyPWE",
    clipStartSeconds: 53,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "since-u-been-gone-kelly-clarkson",
    title: "Since U Been Gone",
    artist: "Kelly Clarkson",
    youtubeUrl: "https://www.youtube.com/watch?v=R7UrFYvl5TE",
    clipStartSeconds: 47,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "crazy-gnarls-barkley",
    title: "Crazy",
    artist: "Gnarls Barkley",
    youtubeUrl: "https://www.youtube.com/watch?v=-N4jf6rtyuw",
    clipStartSeconds: 31,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "poker-face-lady-gaga",
    title: "Poker Face",
    artist: "Lady Gaga",
    youtubeUrl: "https://www.youtube.com/watch?v=bESGLojNYSo",
    clipStartSeconds: 48,
    bucketIds: ["2000s", "global-pop", "dance-edm", "throwbacks"],
  },
  {
    id: "i-gotta-feeling-black-eyed-peas",
    title: "I Gotta Feeling",
    artist: "The Black Eyed Peas",
    youtubeUrl: "https://www.youtube.com/watch?v=uSD4vsh1zDA",
    clipStartSeconds: 57,
    bucketIds: ["2000s", "global-pop", "dance-edm", "throwbacks"],
  },
  {
    id: "somebody-that-i-used-to-know-gotye",
    title: "Somebody That I Used to Know",
    artist: "Gotye feat. Kimbra",
    youtubeUrl: "https://www.youtube.com/watch?v=8UVNT4wvIGY",
    clipStartSeconds: 76,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "call-me-maybe-carly-rae-jepsen",
    title: "Call Me Maybe",
    artist: "Carly Rae Jepsen",
    youtubeUrl: "https://www.youtube.com/watch?v=fWNaR-rxAic",
    clipStartSeconds: 52,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "roar-katy-perry",
    title: "Roar",
    artist: "Katy Perry",
    youtubeUrl: "https://www.youtube.com/watch?v=CevxZvSJLk8",
    clipStartSeconds: 61,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "counting-stars-onerepublic",
    title: "Counting Stars",
    artist: "OneRepublic",
    youtubeUrl: "https://www.youtube.com/watch?v=hT_nvWreIhg",
    clipStartSeconds: 49,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "happy-pharrell-williams",
    title: "Happy",
    artist: "Pharrell Williams",
    youtubeUrl: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
    clipStartSeconds: 45,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "shake-it-off-taylor-swift",
    title: "Shake It Off",
    artist: "Taylor Swift",
    youtubeUrl: "https://www.youtube.com/watch?v=nfWlot6h_JM",
    clipStartSeconds: 46,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "midnight-city-m83",
    title: "Midnight City",
    artist: "M83",
    youtubeUrl: "https://www.youtube.com/watch?v=dX3k_QDnzHE",
    clipStartSeconds: 44,
    bucketIds: ["2010s", "dance-edm", "global-pop"],
  },
  {
    id: "habits-stay-high-tove-lo",
    title: "Habits (Stay High)",
    artist: "Tove Lo",
    youtubeUrl: "https://www.youtube.com/watch?v=oh2LWWORoiM",
    clipStartSeconds: 46,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "stolen-dance-milky-chance",
    title: "Stolen Dance",
    artist: "Milky Chance",
    youtubeUrl: "https://www.youtube.com/watch?v=iX-QaNzd-0Y",
    clipStartSeconds: 45,
    bucketIds: ["2010s", "global-pop"],
  },
  {
    id: "breezeblocks-alt-j",
    title: "Breezeblocks",
    artist: "alt-J",
    youtubeUrl: "https://www.youtube.com/watch?v=rVeMiVU77wo",
    clipStartSeconds: 48,
    bucketIds: ["2010s", "rock-classics"],
  },
  {
    id: "feel-it-still-portugal-the-man",
    title: "Feel It Still",
    artist: "Portugal. The Man",
    youtubeUrl: "https://www.youtube.com/watch?v=pBkHHoOIIn8",
    clipStartSeconds: 42,
    bucketIds: ["2010s", "global-pop", "rock-classics"],
  },
  {
    id: "little-talks-of-monsters-and-men",
    title: "Little Talks",
    artist: "Of Monsters and Men",
    youtubeUrl: "https://www.youtube.com/watch?v=ghb6eDopW8I",
    clipStartSeconds: 52,
    bucketIds: ["2010s", "global-pop", "rock-classics"],
  },
  {
    id: "reptilia-the-strokes",
    title: "Reptilia",
    artist: "The Strokes",
    youtubeUrl: "https://www.youtube.com/watch?v=b8-tXG8KrWs",
    clipStartSeconds: 35,
    bucketIds: ["rock-classics", "2000s", "throwbacks"],
  },
  {
    id: "just-like-heaven-the-cure",
    title: "Just Like Heaven",
    artist: "The Cure",
    youtubeUrl: "https://www.youtube.com/watch?v=n3nPiBai66M",
    clipStartSeconds: 42,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "where-is-my-mind-pixies",
    title: "Where Is My Mind?",
    artist: "Pixies",
    youtubeUrl: "https://www.youtube.com/watch?v=OJ62RzJkYUo",
    clipStartSeconds: 40,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "everlong-foo-fighters",
    title: "Everlong",
    artist: "Foo Fighters",
    youtubeUrl: "https://www.youtube.com/watch?v=hq0rZ3IiyWw",
    clipStartSeconds: 42,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "the-chain-fleetwood-mac",
    title: "The Chain",
    artist: "Fleetwood Mac",
    youtubeUrl: "https://www.youtube.com/watch?v=xwTPvcPYaOo",
    clipStartSeconds: 170,
    bucketIds: ["rock-classics", "throwbacks"],
  },
  {
    id: "fluorescent-adolescent-arctic-monkeys",
    title: "Fluorescent Adolescent",
    artist: "Arctic Monkeys",
    youtubeUrl: "https://www.youtube.com/watch?v=ma9I9VBKPiw",
    clipStartSeconds: 47,
    bucketIds: ["rock-classics", "2000s", "throwbacks"],
  },
  {
    id: "lady-hear-me-tonight-modjo",
    title: "Lady (Hear Me Tonight)",
    artist: "Modjo",
    youtubeUrl: "https://www.youtube.com/watch?v=mMfxI3r_LyA",
    clipStartSeconds: 36,
    bucketIds: ["2000s", "dance-edm", "throwbacks"],
  },
  {
    id: "thats-not-my-name-the-ting-tings",
    title: "That's Not My Name",
    artist: "The Ting Tings",
    youtubeUrl: "https://www.youtube.com/watch?v=v1c2OfAzDTI",
    clipStartSeconds: 45,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "maneater-nelly-furtado",
    title: "Maneater",
    artist: "Nelly Furtado",
    youtubeUrl: "https://www.youtube.com/watch?v=b0XqR7SEE1I",
    clipStartSeconds: 45,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "kids-mgmt",
    title: "Kids",
    artist: "MGMT",
    youtubeUrl: "https://www.youtube.com/watch?v=DngxJlZSpPo",
    clipStartSeconds: 28,
    bucketIds: ["2000s", "global-pop", "throwbacks"],
  },
  {
    id: "enjoy-the-silence-depeche-mode",
    title: "Enjoy the Silence",
    artist: "Depeche Mode",
    youtubeUrl: "https://www.youtube.com/watch?v=aGSKrC7dGcY",
    clipStartSeconds: 45,
    bucketIds: ["throwbacks", "rock-classics"],
  },
  {
    id: "smalltown-boy-bronski-beat",
    title: "Smalltown Boy",
    artist: "Bronski Beat",
    youtubeUrl: "https://www.youtube.com/watch?v=88sARuFu-tc",
    clipStartSeconds: 50,
    bucketIds: ["throwbacks", "dance-edm"],
  },
  {
    id: "shum-go-a",
    title: "SHUM",
    artist: "Go_A",
    youtubeUrl: "https://www.youtube.com/watch?v=U7-dxzp6Jvs",
    clipStartSeconds: 48,
    bucketIds: ["eurovision", "dance-edm"],
  },
  {
    id: "soldi-mahmood",
    title: "Soldi",
    artist: "Mahmood",
    youtubeUrl: "https://www.youtube.com/watch?v=22lISUXgSUw",
    clipStartSeconds: 54,
    bucketIds: ["eurovision", "global-pop"],
  },
  {
    id: "think-about-things-dadi-freyr",
    title: "Think About Things",
    artist: "Daði Freyr",
    youtubeUrl: "https://www.youtube.com/watch?v=1HU7ocv3S2o",
    clipStartSeconds: 39,
    bucketIds: ["eurovision", "dance-edm", "global-pop"],
  },
  {
    id: "fuego-eleni-foureira",
    title: "Fuego",
    artist: "Eleni Foureira",
    youtubeUrl: "https://www.youtube.com/watch?v=eDSgs6syrgg",
    clipStartSeconds: 49,
    bucketIds: ["eurovision", "dance-edm", "global-pop"],
  },
  {
    id: "satisfaction-benny-benassi",
    title: "Satisfaction",
    artist: "Benny Benassi presents The Biz",
    youtubeUrl: "https://www.youtube.com/watch?v=a0fkNdPiIL4",
    clipStartSeconds: 30,
    bucketIds: ["dance-edm", "2000s", "throwbacks"],
  },
  {
    id: "ocean-drive-duke-dumont",
    title: "Ocean Drive",
    artist: "Duke Dumont",
    youtubeUrl: "https://www.youtube.com/watch?v=KDxJlW6cxRk",
    clipStartSeconds: 54,
    bucketIds: ["dance-edm", "2010s", "global-pop"],
  },
] as const satisfies readonly SongCatalogSourceEntry[];
