import { type SongDifficulty, type SongQuizMetadata } from "../song-buckets";

const metadata = (
  quizCategoryId: SongQuizMetadata["quizCategoryId"],
  songs: Record<string, SongDifficulty>,
): Array<[string, SongQuizMetadata]> => {
  return Object.entries(songs).map(([songId, difficulty]) => [
    songId,
    { quizCategoryId, difficulty },
  ]);
};

/**
 * The answer category and difficulty are deliberately curated independently
 * from browsing buckets. A song may be discoverable through several buckets,
 * but every quiz round has exactly one fair distractor pool.
 */
const songQuizMetadataEntries = [
  ...metadata("global-pop", {
    "billie-jean": 1,
    "rolling-in-the-deep": 1,
    "blinding-lights": 1,
    "bad-guy": 1,
    berghain: 5,
    francesca: 4,
    runaway: 3,
    "levitating-dua-lipa": 1,
    "as-it-was-harry-styles": 1,
    "flowers-miley-cyrus": 1,
    "drivers-license-olivia-rodrigo": 2,
    "kill-bill-sza": 2,
  }),
  ...metadata("meme", {
    "the-7th-element": 3,
    "youre-beautiful-but-its-groan-tube": 4,
    "never-gonna-give-you-up": 1,
    ppap: 1,
    sandstorm: 1,
    "crab-rave": 2,
    "running-in-the-90s": 2,
    scatman: 1,
    "coffin-dance": 1,
    buttercup: 3,
    "all-star": 1,
    "gangnam-style": 1,
  }),
  ...metadata("slovenian", {
    "kuku-lele": 3,
    silvo: 4,
    "kej-si": 4,
    "creva-na-plot": 4,
    "all-my-friends-are-dead": 4,
    prjatucki: 4,
    "joker-out-carpe-diem": 1,
    "siddharta-na-soncu": 1,
    "big-foot-mama-nisem-vec-s-tabo": 2,
    "tabu-dobra-vila": 2,
    "kingston-cela-ulica-nori": 1,
    "nina-puslar-to-mi-je-vsec": 2,
    "jan-plestenjak-iz-pekla-do-raja": 2,
    "modrijani-ti-moja-rozica": 1,
    "bepop-moje-sonce": 2,
    "game-over-ubila-si-del-mene": 3,
    "maraaya-here-for-you": 3,
    "zalagasper-sebi": 2,
    "maja-keuc-no-one": 3,
    "lps-disko": 2,
    "tinkara-kovac-round-and-round": 4,
    "raiven-veronika": 2,
    "lea-sirk-hvala-ne": 3,
    "omar-naber-stop": 3,
    "mi2-cista-jeba": 2,
    "flirrt-romeo-in-julija": 3,
    "manca-spik-isaac-palma-oba": 4,
  }),
  ...metadata("balkan", {
    "moja-treba": 4,
    "najjaci-si": 4,
    "zmija-i-zaba": 3,
    aspirin: 2,
    "koktel-ljubavi": 2,
    "barbie-and-ken": 4,
    "bijelo-dugme-djurdjevdan": 1,
    "zdravko-colic-ti-si-mi-u-krvi": 2,
    "oliver-dragojevic-cesarica": 1,
    "bajaga-moji-drugovi": 1,
    "parni-valjak-sve-jos-mirise-na-nju": 2,
    "prljavo-kazaliste-mojoj-majci": 3,
    "crvena-jabuka-tugo-nesreco": 3,
    "dino-merlin-kad-si-rekla-da-me-volis": 2,
    "zeljko-joksimovic-lane-moje": 1,
    "marija-serifovic-molitva": 1,
    "severina-moja-stikla": 2,
    "hari-mata-hari-lejla": 2,
    "dubioza-kolektiv-kazu": 2,
    "senidah-sladjana": 2,
    "konstrakta-in-corpore-sano": 1,
    "baby-lasagna-rim-tim-tagi-dim": 1,
    "hurricane-loco-loco": 3,
    "teya-dora-ramonda": 2,
    "jala-buba-coby-ona-e": 3,
    "severina-ministarke-uno-momento": 2,
  }),
  ...metadata("rock-classics", {
    "bohemian-rhapsody": 1,
    "smells-like-teen-spirit": 1,
    ymca: 1,
    "dancing-queen-abba": 1,
    "stayin-alive-bee-gees": 1,
    "september-earth-wind-fire": 2,
    "i-will-survive-gloria-gaynor": 1,
    "rocket-man-elton-john": 2,
    "wonderwall-oasis": 1,
    "creep-radiohead": 1,
    "mr-brightside-the-killers": 1,
    "viva-la-vida-coldplay": 1,
    "in-the-end-linkin-park": 1,
    "seven-nation-army-the-white-stripes": 1,
  }),
  ...metadata("throwbacks", {
    "take-on-me": 1,
    "lemon-tree": 2,
    "thriller-michael-jackson": 1,
    "i-wanna-dance-with-somebody-whitney-houston": 1,
    "girls-just-want-to-have-fun-cyndi-lauper": 1,
    "like-a-prayer-madonna": 1,
    "wannabe-spice-girls": 1,
    "baby-one-more-time-britney-spears": 1,
    "i-want-it-that-way-backstreet-boys": 1,
  }),
  ...metadata("2000s", {
    "jerk-it-out": 3,
    "hey-ya-outkast": 1,
    "crazy-in-love-beyonce": 1,
    "lose-yourself-eminem": 1,
    "bad-romance-lady-gaga": 1,
    "umbrella-rihanna": 1,
    "one-more-time-daft-punk": 2,
    "everytime-we-touch-cascada": 2,
    "toxic-britney-spears": 1,
    "complicated-avril-lavigne": 2,
    "since-u-been-gone-kelly-clarkson": 2,
    "crazy-gnarls-barkley": 2,
    "poker-face-lady-gaga": 1,
    "i-gotta-feeling-black-eyed-peas": 1,
  }),
  ...metadata("2010s", {
    "uptown-funk-mark-ronson-ft-bruno-mars": 1,
    "shape-of-you-ed-sheeran": 1,
    "despacito-luis-fonsi": 1,
    "blank-space-taylor-swift": 1,
    "somebody-that-i-used-to-know-gotye": 1,
    "call-me-maybe-carly-rae-jepsen": 1,
    "roar-katy-perry": 1,
    "counting-stars-onerepublic": 1,
    "happy-pharrell-williams": 1,
    "shake-it-off-taylor-swift": 1,
  }),
  ...metadata("eurovision", {
    "bara-bada-bastu": 2,
    "euphoria-loreen": 1,
    "zitti-e-buoni-maneskin": 2,
    "rise-like-a-phoenix-conchita-wurst": 2,
    "fairytale-alexander-rybak": 1,
    "hard-rock-hallelujah-lordi": 2,
    "cha-cha-cha-kaarija": 1,
    "dancing-lasha-tumbai-verka-serduchka": 2,
    "wild-dances-ruslana": 3,
    "heroes-mans-zelmerlow": 3,
  }),
  ...metadata("dance-edm", {
    "london-song": 5,
    "baby-im-yours": 3,
    "wake-me-up-avicii": 1,
    "titanium-david-guetta-sia": 1,
    "summer-calvin-harris": 2,
    "dont-you-worry-child-swedish-house-mafia": 2,
    "party-rock-anthem-lmfao": 1,
    "lean-on-major-lazer-dj-snake": 2,
    "clarity-zedd": 3,
    "rather-be-clean-bandit": 2,
  }),
];

const metadataSongIds = songQuizMetadataEntries.map(([songId]) => songId);
if (new Set(metadataSongIds).size !== metadataSongIds.length) {
  throw new Error("Quiz metadata must declare every song id exactly once.");
}

export const songQuizMetadataById: Readonly<Record<string, SongQuizMetadata>> =
  Object.fromEntries(songQuizMetadataEntries);
