import { type SongCatalogSourceEntry } from "../song-buckets";

export const slovenianSongAdditions = [
  {
    id: "joker-out-carpe-diem",
    title: "Carpe Diem",
    artist: "Joker Out",
    youtubeUrl: "https://www.youtube.com/watch?v=zDBSIGITdY4",
    clipStartSeconds: 49,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "siddharta-na-soncu",
    title: "Na soncu",
    artist: "Siddharta",
    youtubeUrl: "https://www.youtube.com/watch?v=q3wFOdAYSs8",
    clipStartSeconds: 45,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "big-foot-mama-nisem-vec-s-tabo",
    title: "Nisem več s tabo",
    artist: "Big Foot Mama",
    youtubeUrl: "https://www.youtube.com/watch?v=D2ElnN5gwJI",
    clipStartSeconds: 48,
    bucketIds: ["slovenian", "rock-classics"],
  },
  {
    id: "tabu-dobra-vila",
    title: "Dobra vila",
    artist: "Tabu",
    youtubeUrl: "https://www.youtube.com/watch?v=3b8iqsEAUh8",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "kingston-cela-ulica-nori",
    title: "Cela ulica nori",
    artist: "Kingston",
    youtubeUrl: "https://www.youtube.com/watch?v=w_PIxfNz5E0",
    clipStartSeconds: 47,
    bucketIds: ["slovenian"],
  },
  {
    id: "nina-puslar-to-mi-je-vsec",
    title: "To mi je všeč",
    artist: "Nina Pušlar",
    youtubeUrl: "https://www.youtube.com/watch?v=sErniAExkZI",
    clipStartSeconds: 50,
    bucketIds: ["slovenian", "2010s"],
  },
  {
    id: "jan-plestenjak-iz-pekla-do-raja",
    title: "Iz pekla do raja",
    artist: "Jan Plestenjak",
    youtubeUrl: "https://www.youtube.com/watch?v=IXpmRIJqSA0",
    clipStartSeconds: 50,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "modrijani-ti-moja-rozica",
    title: "Ti, moja rožica",
    artist: "Modrijani",
    youtubeUrl: "https://www.youtube.com/watch?v=LCjfC6IR6B8",
    clipStartSeconds: 42,
    bucketIds: ["slovenian", "2010s"],
  },
  {
    id: "bepop-moje-sonce",
    title: "Moje sonce",
    artist: "Bepop",
    youtubeUrl: "https://www.youtube.com/watch?v=et_9avVihsE",
    clipStartSeconds: 45,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "game-over-ubila-si-del-mene",
    title: "Ubila si del mene",
    artist: "Game Over",
    youtubeUrl: "https://www.youtube.com/watch?v=cMJu46KpZWs",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "maraaya-here-for-you",
    title: "Here for You",
    artist: "Maraaya",
    youtubeUrl: "https://www.youtube.com/watch?v=y0MVn4XENkI",
    clipStartSeconds: 61,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "zalagasper-sebi",
    title: "Sebi",
    artist: "zalagasper",
    youtubeUrl: "https://www.youtube.com/watch?v=vleF8-gAn_U",
    clipStartSeconds: 54,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "maja-keuc-no-one",
    title: "No One",
    artist: "Maja Keuc",
    youtubeUrl: "https://www.youtube.com/watch?v=SXjuJXGFST0",
    clipStartSeconds: 62,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "lps-disko",
    title: "Disko",
    artist: "LPS",
    youtubeUrl: "https://www.youtube.com/watch?v=g8Ezl7xucCU",
    clipStartSeconds: 48,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "tinkara-kovac-round-and-round",
    title: "Round and Round",
    artist: "Tinkara Kovač",
    youtubeUrl: "https://www.youtube.com/watch?v=ZMpNkCOMaGU",
    clipStartSeconds: 58,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "raiven-veronika",
    title: "Veronika",
    artist: "Raiven",
    youtubeUrl: "https://www.youtube.com/watch?v=uWcSsi7SliI",
    clipStartSeconds: 59,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "lea-sirk-hvala-ne",
    title: "Hvala, ne!",
    artist: "Lea Sirk",
    youtubeUrl: "https://www.youtube.com/watch?v=Xzaa22agPqA",
    clipStartSeconds: 54,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "omar-naber-stop",
    title: "Stop",
    artist: "Omar Naber",
    youtubeUrl: "https://www.youtube.com/watch?v=l2Mp_ltL36g",
    clipStartSeconds: 60,
    bucketIds: ["slovenian", "2000s", "eurovision"],
  },
  {
    id: "mi2-cista-jeba",
    title: "Čista jeba",
    artist: "Mi2",
    youtubeUrl: "https://www.youtube.com/watch?v=_u8CpQdZLMA",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2010s", "rock-classics"],
  },
  {
    id: "flirrt-romeo-in-julija",
    title: "Romeo in Julija",
    artist: "FLIRRT",
    youtubeUrl: "https://www.youtube.com/watch?v=Pe0RbB7sIUk",
    clipStartSeconds: 51,
    bucketIds: ["slovenian", "rock-classics"],
  },
  {
    id: "manca-spik-isaac-palma-oba",
    title: "Oba",
    artist: "Manca Špik & Isaac Palma",
    youtubeUrl: "https://www.youtube.com/watch?v=mUtLpLSU-1Y",
    clipStartSeconds: 55,
    bucketIds: ["slovenian", "2010s"],
  },
  {
    id: "dan-d-voda",
    title: "Voda",
    artist: "Dan D",
    youtubeUrl: "https://www.youtube.com/watch?v=rr_x41eIgB4",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "koala-voice-go-disco-go",
    title: "Go Disco, Go",
    artist: "Koala Voice",
    youtubeUrl: "https://www.youtube.com/watch?v=QscWr0JxWrU",
    clipStartSeconds: 35,
    bucketIds: ["slovenian", "2010s", "rock-classics"],
  },
  {
    id: "siddharta-napoj",
    title: "Napoj",
    artist: "Siddharta",
    youtubeUrl: "https://www.youtube.com/watch?v=G6whSCaK8gQ",
    clipStartSeconds: 51,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "big-foot-mama-led-s-severa",
    title: "Led s severa",
    artist: "Big Foot Mama",
    youtubeUrl: "https://www.youtube.com/watch?v=ExmoTeC3e5g",
    clipStartSeconds: 48,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "niet-lep-dan-za-smrt",
    title: "Lep dan za smrt",
    artist: "Niet",
    youtubeUrl: "https://www.youtube.com/watch?v=MJZRYU0geOg",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "rock-classics", "throwbacks"],
  },
  {
    id: "zmelkoow-bit",
    title: "Bit",
    artist: "Zmelkoow",
    youtubeUrl: "https://www.youtube.com/watch?v=1HnMi9iYxSs",
    clipStartSeconds: 44,
    bucketIds: ["slovenian", "rock-classics", "throwbacks"],
  },
  {
    id: "mrfy-umru-zate",
    title: "Umru zate",
    artist: "MRFY",
    youtubeUrl: "https://www.youtube.com/watch?v=i5R_zRhcOVs",
    clipStartSeconds: 36,
    bucketIds: ["slovenian"],
  },
  {
    id: "mrfy-zaljubila",
    title: "Zaljubila",
    artist: "MRFY",
    youtubeUrl: "https://www.youtube.com/watch?v=_xXvutuerHk",
    clipStartSeconds: 42,
    bucketIds: ["slovenian"],
  },
  {
    id: "mrfy-fat-kid",
    title: "Fat Kid",
    artist: "MRFY",
    youtubeUrl: "https://www.youtube.com/watch?v=wmnvoMwnTDQ",
    clipStartSeconds: 34,
    bucketIds: ["slovenian"],
  },
  {
    id: "adi-smolar-dalec-je-za-naju-pomlad",
    title: "Daleč je za naju pomlad",
    artist: "Adi Smolar",
    youtubeUrl: "https://www.youtube.com/watch?v=F-9Nz3qlXnY",
    clipStartSeconds: 40,
    bucketIds: ["slovenian"],
  },
  {
    id: "adi-smolar-je-treba-delat",
    title: "Je treba delat",
    artist: "Adi Smolar",
    youtubeUrl: "https://www.youtube.com/watch?v=G0D9JyiauOQ",
    clipStartSeconds: 32,
    bucketIds: ["slovenian"],
  },
  {
    id: "severa-gjurin-kadar-sva-sama",
    title: "Kadar sva sama",
    artist: "Severa Gjurin",
    youtubeUrl: "https://www.youtube.com/watch?v=JDguoN6zJM0",
    clipStartSeconds: 42,
    bucketIds: ["slovenian"],
  },
  {
    id: "severa-gjurin-ali-je-se-kaj-prostora-tam-na-jugu",
    title: "Ali je še kaj prostora tam na jugu",
    artist: "Severa Gjurin",
    youtubeUrl: "https://www.youtube.com/watch?v=2BfCVgmROiU",
    clipStartSeconds: 38,
    bucketIds: ["slovenian"],
  },
  {
    id: "gal-gjurin-kaj-vse-bi-dal",
    title: "Kaj vse bi dal",
    artist: "Gal Gjurin",
    youtubeUrl: "https://www.youtube.com/watch?v=wE4M9j_dSRY",
    clipStartSeconds: 43,
    bucketIds: ["slovenian"],
  },
  {
    id: "gal-gjurin-dusa-in-telo",
    title: "Duša in telo",
    artist: "Gal Gjurin",
    youtubeUrl: "https://www.youtube.com/watch?v=Sx4hQPa88ws",
    clipStartSeconds: 42,
    bucketIds: ["slovenian"],
  },
  {
    id: "capital-crew-cptlj",
    title: "CPTLJ",
    artist: "Capital Crew",
    youtubeUrl: "https://www.youtube.com/watch?v=b49wksb95eo",
    clipStartSeconds: 26,
    bucketIds: ["slovenian"],
  },
  {
    id: "capital-crew-chardonnay",
    title: "Chardonnay",
    artist: "Capital Crew",
    youtubeUrl: "https://www.youtube.com/watch?v=FKOl-DV_PG4",
    clipStartSeconds: 33,
    bucketIds: ["slovenian"],
  },
  {
    id: "emkej-one-love",
    title: "One Love",
    artist: "Emkej",
    youtubeUrl: "https://www.youtube.com/watch?v=Ih8qMtDgIME",
    clipStartSeconds: 30,
    bucketIds: ["slovenian"],
  },
  {
    id: "emkej-marleybor",
    title: "Marleybor",
    artist: "Emkej",
    youtubeUrl: "https://www.youtube.com/watch?v=FkfWRnrntIo",
    clipStartSeconds: 30,
    bucketIds: ["slovenian"],
  },
  {
    id: "mrigo-ghet-pazim-premagan",
    title: "Pazim/Premagan",
    artist: "Mrigo & Ghet",
    youtubeUrl: "https://www.youtube.com/watch?v=vPbqkNJQZmM",
    clipStartSeconds: 28,
    bucketIds: ["slovenian"],
  },
  {
    id: "mrigo-ghet-fonkdat",
    title: "Fonkdat",
    artist: "Mrigo & Ghet",
    youtubeUrl: "https://www.youtube.com/watch?v=ktnsm-wV5pc",
    clipStartSeconds: 31,
    bucketIds: ["slovenian"],
  },
  {
    id: "nina-puslar-tople-oci",
    title: "Tople oči",
    artist: "Nina Pušlar",
    youtubeUrl: "https://www.youtube.com/watch?v=uPwXHMlYiR8",
    clipStartSeconds: 45,
    bucketIds: ["slovenian"],
  },
  {
    id: "nina-puslar-ni-ona",
    title: "Ni ona",
    artist: "Nina Pušlar",
    youtubeUrl: "https://www.youtube.com/watch?v=zork30wQiaY",
    clipStartSeconds: 43,
    bucketIds: ["slovenian"],
  },
  {
    id: "hamo-tribute-2-love-rozice",
    title: "Rožice",
    artist: "Hamo & Tribute 2 Love",
    youtubeUrl: "https://www.youtube.com/watch?v=g17YxxD85io",
    clipStartSeconds: 40,
    bucketIds: ["slovenian"],
  },
  {
    id: "batista-cadillac-magnolije",
    title: "Magnolije",
    artist: "Batista Cadillac",
    youtubeUrl: "https://www.youtube.com/watch?v=cVJBsbPjysg",
    clipStartSeconds: 35,
    bucketIds: ["slovenian"],
  },
  {
    id: "jet-black-diamonds-se-zadnjic",
    title: "Še zadnjič",
    artist: "Jet Black Diamonds",
    youtubeUrl: "https://www.youtube.com/watch?v=IhHIAmOgH4A",
    clipStartSeconds: 43,
    bucketIds: ["slovenian"],
  },
  {
    id: "alo-stari-nea-vem-kam",
    title: "Nea vem kam",
    artist: "Alo!Stari",
    youtubeUrl: "https://www.youtube.com/watch?v=vv_2MzCNq08",
    clipStartSeconds: 35,
    bucketIds: ["slovenian"],
  },
  {
    id: "fed-horses-ti-ne-poznas-konjev",
    title: "Ti ne poznaš konjev",
    artist: "Fed Horses",
    youtubeUrl: "https://www.youtube.com/watch?v=JfhHB9aF_QU",
    clipStartSeconds: 41,
    bucketIds: ["slovenian"],
  },
  {
    id: "cedahuci-ce-hoces-grem",
    title: "Če hočeš, grem",
    artist: "Čedahuči",
    youtubeUrl: "https://www.youtube.com/watch?v=FRB_8PiwThU",
    clipStartSeconds: 40,
    bucketIds: ["slovenian"],
  },
  {
    id: "kokosy-planeti-se-vrtijo",
    title: "Planeti se vrtijo",
    artist: "KOKOSY",
    youtubeUrl: "https://www.youtube.com/watch?v=Pdl9wdxjzFw",
    clipStartSeconds: 36,
    bucketIds: ["slovenian"],
  },
  {
    id: "kokosy-lana-ne",
    title: "Lana ne",
    artist: "KOKOSY",
    youtubeUrl: "https://www.youtube.com/watch?v=buwqxCJ6mKQ",
    clipStartSeconds: 35,
    bucketIds: ["slovenian"],
  },
  {
    id: "kokosy-mislim-nate",
    title: "Mislim nate",
    artist: "KOKOSY",
    youtubeUrl: "https://www.youtube.com/watch?v=eRMrfQ_di7E",
    clipStartSeconds: 40,
    bucketIds: ["slovenian"],
  },
] as const satisfies readonly SongCatalogSourceEntry[];
