import { type SongCatalogEntry } from "../song-buckets";

export const slovenianSongAdditions = [
  {
    id: "joker-out-carpe-diem",
    title: "Carpe Diem",
    artist: "Joker Out",
    youtubeUrl: "https://www.youtube.com/watch?v=zDBSIGITdY4",
    clipStartSeconds: 49,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "siddharta-na-soncu",
    title: "Na soncu",
    artist: "Siddharta",
    youtubeUrl: "https://www.youtube.com/watch?v=q3wFOdAYSs8",
    clipStartSeconds: 45,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "big-foot-mama-nisem-vec-s-tabo",
    title: "Nisem več s tabo",
    artist: "Big Foot Mama",
    youtubeUrl: "https://www.youtube.com/watch?v=D2ElnN5gwJI",
    clipStartSeconds: 48,
    bucketIds: ["slovenian", "rock-classics"],
  },
  {
    id: "tabu-dobra-vila",
    title: "Dobra vila",
    artist: "Tabu",
    youtubeUrl: "https://www.youtube.com/watch?v=3b8iqsEAUh8",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2000s", "rock-classics"],
  },
  {
    id: "kingston-cela-ulica-nori",
    title: "Cela ulica nori",
    artist: "Kingston",
    youtubeUrl: "https://www.youtube.com/watch?v=w_PIxfNz5E0",
    clipStartSeconds: 47,
    bucketIds: ["slovenian"],
  },
  {
    id: "nina-puslar-to-mi-je-vsec",
    title: "To mi je všeč",
    artist: "Nina Pušlar",
    youtubeUrl: "https://www.youtube.com/watch?v=sErniAExkZI",
    clipStartSeconds: 50,
    bucketIds: ["slovenian", "2010s"],
  },
  {
    id: "jan-plestenjak-iz-pekla-do-raja",
    title: "Iz pekla do raja",
    artist: "Jan Plestenjak",
    youtubeUrl: "https://www.youtube.com/watch?v=IXpmRIJqSA0",
    clipStartSeconds: 50,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "modrijani-ti-moja-rozica",
    title: "Ti, moja rožica",
    artist: "Modrijani",
    youtubeUrl: "https://www.youtube.com/watch?v=LCjfC6IR6B8",
    clipStartSeconds: 42,
    bucketIds: ["slovenian", "2010s"],
  },
  {
    id: "bepop-moje-sonce",
    title: "Moje sonce",
    artist: "Bepop",
    youtubeUrl: "https://www.youtube.com/watch?v=et_9avVihsE",
    clipStartSeconds: 45,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "game-over-ubila-si-del-mene",
    title: "Ubila si del mene",
    artist: "Game Over",
    youtubeUrl: "https://www.youtube.com/watch?v=cMJu46KpZWs",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2000s"],
  },
  {
    id: "maraaya-here-for-you",
    title: "Here for You",
    artist: "Maraaya",
    youtubeUrl: "https://www.youtube.com/watch?v=y1c7gDOaFY0",
    clipStartSeconds: 61,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "zalagasper-sebi",
    title: "Sebi",
    artist: "zalagasper",
    youtubeUrl: "https://www.youtube.com/watch?v=vGtPNQ6g6Ng",
    clipStartSeconds: 54,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "maja-keuc-no-one",
    title: "No One",
    artist: "Maja Keuc",
    youtubeUrl: "https://www.youtube.com/watch?v=5vqjb2OYnYs",
    clipStartSeconds: 62,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "lps-disko",
    title: "Disko",
    artist: "LPS",
    youtubeUrl: "https://www.youtube.com/watch?v=g8Ezl7xucCU",
    clipStartSeconds: 48,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "tinkara-kovac-round-and-round",
    title: "Round and Round",
    artist: "Tinkara Kovač",
    youtubeUrl: "https://www.youtube.com/watch?v=CiwM1sY3u0s",
    clipStartSeconds: 58,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "raiven-veronika",
    title: "Veronika",
    artist: "Raiven",
    youtubeUrl: "https://www.youtube.com/watch?v=l86DxpRnz5M",
    clipStartSeconds: 59,
    bucketIds: ["slovenian", "eurovision"],
  },
  {
    id: "lea-sirk-hvala-ne",
    title: "Hvala, ne!",
    artist: "Lea Sirk",
    youtubeUrl: "https://www.youtube.com/watch?v=fBU0_hfST_o",
    clipStartSeconds: 54,
    bucketIds: ["slovenian", "2010s", "eurovision"],
  },
  {
    id: "omar-naber-stop",
    title: "Stop",
    artist: "Omar Naber",
    youtubeUrl: "https://www.youtube.com/watch?v=qUTIYik9cRA",
    clipStartSeconds: 60,
    bucketIds: ["slovenian", "2000s", "eurovision"],
  },
  {
    id: "mi2-cista-jeba",
    title: "Čista jeba",
    artist: "Mi2",
    youtubeUrl: "https://www.youtube.com/watch?v=_u8CpQdZLMA",
    clipStartSeconds: 52,
    bucketIds: ["slovenian", "2010s", "rock-classics"],
  },
  {
    id: "flirrt-romeo-in-julija",
    title: "Romeo in Julija",
    artist: "FLIRRT",
    youtubeUrl: "https://www.youtube.com/watch?v=Pe0RbB7sIUk",
    clipStartSeconds: 51,
    bucketIds: ["slovenian", "rock-classics"],
  },
  {
    id: "manca-spik-isaac-palma-oba",
    title: "Oba",
    artist: "Manca Špik & Isaac Palma",
    youtubeUrl: "https://www.youtube.com/watch?v=mUtLpLSU-1Y",
    clipStartSeconds: 55,
    bucketIds: ["slovenian", "2010s"],
  },
] as const satisfies readonly SongCatalogEntry[];
