import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    "harness/visual": "src/harness/visual.ts",
    "mcp-config": "src/mcp-config.ts",
    agent: "src/agent.ts",
    context: "src/context.ts",
    controller: "src/controller.ts",
    dev: "src/dev.ts",
    "game-session": "src/game-session.ts",
    "game-session-broker": "src/game-session-broker.ts",
    games: "src/games.ts",
    logs: "src/logs.ts",
    "platform-auth": "src/platform-auth.ts",
    "platform-game-media": "src/platform-game-media.ts",
    "platform-games": "src/platform-games.ts",
    quality: "src/quality.ts",
    release: "src/release.ts",
    visual: "src/visual.ts",
    "tooling/agent-contract": "src/tooling/agent-contract.ts",
    "tooling/hold-runtime-host": "src/tooling/hold-runtime-host.ts",
    "tooling/inspect-airjam-agent": "src/tooling/inspect-airjam-agent.ts",
    "tooling/list-visual-scenarios": "src/tooling/list-visual-scenarios.ts",
    "tooling/managed-dev-supervisor": "src/tooling/managed-dev-supervisor.ts",
    "tooling/run-visual-capture": "src/tooling/run-visual-capture.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "es2022",
  platform: "node",
});
