export enum ErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_FULL = "ROOM_FULL",
  INVALID_APP_ID = "INVALID_APP_ID",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  CONNECTION_FAILED = "CONNECTION_FAILED",
  ALREADY_CONNECTED = "ALREADY_CONNECTED",
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  INVALID_ROOM_CODE = "INVALID_ROOM_CODE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export interface ServerErrorPayload {
  code: ErrorCode | string;
  message: string;
  details?: unknown;
}
