// Generated by scripts/platform/lib/platform-schema-head-generator.mjs.
// Do not edit by hand.

export const PLATFORM_SCHEMA_CONTRACT_VERSION = 1 as const;

export const platformSchemaHead = {
  tag: "0040_host_grant_consumption",
  createdAt: 1788939243862,
  hash: "f8b2cd744cfaa64055fa79dc0ba7972757466b7a47729f798a12715e85bec7e7",
  catalogDigest:
    "7dfb90a08817705e8b9d74605904cecb2eccc67310165f81ec040c02554d46e7",
} as const;
