// Generated by scripts/platform/lib/platform-schema-head-generator.mjs.
// Do not edit by hand.

export const PLATFORM_SCHEMA_CONTRACT_VERSION = 1 as const;

export const platformSchemaHead = {
  tag: "0044_release_report_submission_keys",
  createdAt: 1789246514172,
  hash: "7ac5263720a4b795c9b4c3ada09c66ab5ee5b8e7329480822eed0fac7ba7535c",
  catalogDigest:
    "9ec71182da14139f7892104fa3499822f9d0d55e44f5349ea2db0305bb597244",
} as const;
